INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.21.0-f20c78af53c615fc96b6e160e07f44cb6b337643.
[job sleep] /Users/kumarn1/work/ridgeback/tests/toil_mock/toil_3.21/failed/tmp/work/toil-ec911c2c-f668-4c05-86fc-2b54869b8026-26824500935055/tmpe29eotk2/90abbdd6-b084-4e9d-a937-b3cb7beb86c1/tyll6wafw/tmp-outy_arlomc$ sleep \
    -h
INFO:cwltool:[job sleep] /Users/kumarn1/work/ridgeback/tests/toil_mock/toil_3.21/failed/tmp/work/toil-ec911c2c-f668-4c05-86fc-2b54869b8026-26824500935055/tmpe29eotk2/90abbdd6-b084-4e9d-a937-b3cb7beb86c1/tyll6wafw/tmp-outy_arlomc$ sleep \
    -h
usage: sleep seconds
[job sleep] completed permanentFail
WARNING:cwltool:[job sleep] completed permanentFail
Traceback (most recent call last):
  File "/Users/kumarn1/work/toil/toil_3.21.1/toil/src/toil/worker.py", line 366, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
  File "/Users/kumarn1/work/toil/toil_3.21.1/toil/src/toil/job.py", line 1392, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/Users/kumarn1/work/toil/toil_3.21.1/toil/src/toil/job.py", line 1329, in _run
    return self.run(fileStore)
  File "/Users/kumarn1/work/toil/toil_3.21.1/toil/src/toil/cwl/cwltoil.py", line 626, in run
    raise cwltool.errors.WorkflowException(status)
cwltool.errors.WorkflowException: permanentFail
ERROR:toil.worker:Exiting the worker because of a failed job on host lski2325
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///Users/kumarn1/work/ridgeback/tests/toil_mock/test_cwl/sleep.cwl#simpleWorkflow/sleep/sleep' sleep kind-file_Users_kumarn1_work_ridgeback_tests_toil_mock_test_cwl_sleep.cwl_simpleWorkflow_sleep_sleep/instanceftiko2ha with ID kind-file_Users_kumarn1_work_ridgeback_tests_toil_mock_test_cwl_sleep.cwl_simpleWorkflow_sleep_sleep/instanceftiko2ha to 0
